### ISSUE TITLE
IP Mapping updates

### ISSUE THREAD

**Issue by inonbaguio** [smalldogs/ip2country#1]
Just an inquiry. Once we've installed the package. How are we going to update the ip's from <code>laravel+ip2country</code> table once you have updated your ip mappings?

**Comment by lowiebenoot** [comment]
+1
Will there be a migration that will add new records to the table?

**Comment by brwnll** [comment]
Sorry for the delayed response @lowiebenoot & @inonbaguio. I've just updated the mappings with MaxMind's Feb 4th 2015 CSV release.

After updating the package via `composer update` or `composer update smalldogs/ip2country`, run the migration `php artisan migrate --package="smalldogs/ip2country"`  and it should update you to the latest IP mapping.

Although, as an FYI, cross country IP address don't appear to change often, so I wouldn't fret about having mappings that are a few months old.

Thanks for the interest.
