### ISSUE TITLE
Change classname so migration rollback will work

### ISSUE THREAD

**Issue by 9livesdevelopment** [smalldogs/ip2country#3]
I tried to rollback the migration, but it wouldn't work as Laravel determines the classname based on the table name resulting in:

CreateLaravelIpcountryTable

However your classname is:

CreateLaravelIpCountryTable (notice Country vs country)

Either the classname or the table name have to change in order for the rollback to work. 

Cheers

**Comment by brwnll** [comment]
Thanks for pointing that out. Fixed.
